### ISSUE TITLE
Wohin nur mit den Tasks?

### ISSUE THREAD

**Issue by LEMettler** [Lmeerlu/EntityTask#1]
> Eine Gute Nacht Geschichte, geschrieben von Larry Maulwurf

Android Studio hat eine Schwäche, wenns um den bidirektionalen Umgang zwischen Activities geht. Folgendes:
Wir haben eine ArrayList, die die gesamten Tasks unserer App speichert, egal ob Custom-,Weekly- oder MonthlyTask. Polymorphie du Haiopai.
Tasks werden  aber nun mal nur im Taskcreator erzeugt, aber dort können/wollen wir die Liste nicht speichern, da momentan die Taskanzeige und später auch unser kalender zugriff auf die Liste brauchen. Am sinnvollsten ist es die Liste in der taskActivity zu speichern, da sie dort am meisten gebraucht wird und direkt über dem Taskcreator liegt (hierarchisch gesehen). Nun möchte JavaMaba uns aber keine bidrektionale beziehung zwischen taskcreatorActivity und Taskactvity herstellen lassen. 
Und nochschlimmer: Der Weg über einen Returnwert ist auch steinig und schwer, aber möglich. Siehe 

[https://stackoverflow.com/questions/14785806/android-how-to-make-an-activity-return-results-to-the-activity-which-calls-it?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)

Einziges Problem: **Ein Objekt kann irgendwie nicht als Returnwert verwendet werden um es direkt auf die List zu schieben. Das ist hier vorrangig das Problem.**

TL;DR:
finde einen weg, wie ein in der TaskcreatorActivity erzeugter Task in der tasks-Arraylist der TaskActivity gespeichert werden kann. thx

**Comment by Lmeerlu** [comment]
erledigt: eigenes Objekt "TaskStorage"

**Comment by LEMettler** [comment]
erledigt: eigenes Objekt "TaskStorage"
