### ISSUE TITLE
Weekly-Tasks

### ISSUE THREAD

**Issue by LEMettler** [Lmeerlu/EntityTask#11]
Erstellen der Weekly-Tasks, ich hab euch ne komplette Anleitung in TaskCreator geschrieben. Im Endeffekt müsst ihr nur den Dialog erstellen, der ein Fragment anzeigt und daraus Infos pullen.
Macht was.

**Comment by Commoned** [comment]
aye aye chef coming soon (I tried und stehe wegen android studio kurz vor dem allgemein annerkannten suizid)

**Comment by LEMettler** [comment]
tja...
